"""Auto Test Core Module - Core utilities for automated testing."""

from .config_manager import (
    APIConfig,
    BrowserConfig,
    ConfigManager,
    EndpointConfig,
    EnvironmentSecurityError,
    EnvironmentType,
    get_config,
    get_environment,
    validate_environment,
)
from .exception_handler import (
    APIError,
    AssertionError,
    AuthenticationError,
    BrowserError,
    ConfigError,
    DataError,
    EnvironmentError,
    ErrorCode,
    ErrorContext,
    ErrorHandler,
    ErrorReporter,
    NetworkError,
    TestFrameworkError,
    TimeoutError,
    ValidationError,
    get_error_handler,
    handle_errors,
    retry_on_error,
    safe_execute,
    setup_default_error_handlers,
)
from .test_data_factory import (
    DataValidationError,
    SchemaBasedFactory,
    TestDataFactory,
    get_schema_factory,
    get_test_data_factory,
)

__all__ = [
    # Config Manager
    "ConfigManager",
    "get_config",
    "get_environment",
    "validate_environment",
    "EnvironmentType",
    "EnvironmentSecurityError",
    "EndpointConfig",
    "BrowserConfig",
    "APIConfig",
    # Test Data Factory
    "TestDataFactory",
    "SchemaBasedFactory",
    "get_test_data_factory",
    "get_schema_factory",
    "DataValidationError",
    # Exception Handler
    "ErrorHandler",
    "ErrorReporter",
    "ErrorCode",
    "ErrorContext",
    "TestFrameworkError",
    "EnvironmentError",
    "ConfigError",
    "AuthenticationError",
    "NetworkError",
    "TimeoutError",
    "ValidationError",
    "DataError",
    "BrowserError",
    "APIError",
    "AssertionError",
    "handle_errors",
    "retry_on_error",
    "safe_execute",
    "get_error_handler",
    "setup_default_error_handlers",
]
